### ISSUE TITLE
Demo analytics code

### ISSUE THREAD

**Issue by scosman** [CriticalMoments/CMSaasStarter#101]
We could/should have a quick example of how to add analytics. We don't need to pick a provider, let's leave that to the user. But for a SvelteKit noob, we can tell them where to put it.

Tasks:

- [ ] Add comment where the analytics JS code should be injected. Probably `app.html`? Can be as simple as 
- [ ] Add a step in README guide for replacing that comment with the tracker of your choice, with links to GA, PostHog, Plausible docs for getting your code/ID.

**Comment by evlim** [comment]
#159 Is something like this too complicated?
