### ISSUE TITLE
User Emailer & Welcome Email

### ISSUE THREAD

**Issue by scosman** [CriticalMoments/CMSaasStarter#102]
We should add a method to email a user. 

- [x] Nice simple API that takes a user, subject, plaintext body, html body, and sends it
- [x] Some simple way of doing templating. Ideally just plain old svelte `Component.render`? Open to ideas here.
- [x] Use Resend API like admin_mailer
- [x] Demo use case of of a welcome email: show all the above working together in nice clean example.

**Comment by kryanbeane** [comment]
+1

**Comment by scosman** [comment]
I’m working on this. Should push it later today.

**Comment by scosman** [comment]
Fixed by https://github.com/CriticalMoments/CMSaasStarter/pull/104
