### ISSUE TITLE
Unsubscribe support for email

### ISSUE THREAD

**Issue by scosman** [CriticalMoments/CMSaasStarter#107]
I added email. I didn't add unsubscribe since there's only 1 email so far, not a long running mailing list. However, others will probably add so this would be good to have.

- [ ] Add a bool unsubscribed property to the profile table
- [ ] Update sendUserEmail function to check unsubscribed property, and not send if unsubscribed
- [ ] In the email section of settings add an "Unsubscribe" button (which changes to "Re-Subscribe" when unsubscribed), which is functional, and sets DB property. 
- [ ] Add unsubscribe link to `/account/settings?unsubscribe` to email templates

**Comment by evgenyneu** [comment]
Hi @scosman, can I work on this please?
