### ISSUE TITLE
Stripe webhook missing?

### ISSUE THREAD

**Issue by ndamofli** [CriticalMoments/CMSaasStarter#12]
I can't seem to understand how stripe updates the database when there are billing errors. Can you please help me understand.?

**Comment by scosman** [comment]
We don’t duplicate the Stripe state in Postgres, so there isn’t a Webhook. Pages like the admin billing page call the stripe API for current subscription status. You can use the same pattern shown there for fetching subscription/billing status.

Webhooks to save it in Postgres might be a nice addition, but isn’t planned.
