### ISSUE TITLE
Documentation page as a part of the starter

### ISSUE THREAD

**Issue by fyodorio** [CriticalMoments/CMSaasStarter#120]
As many SaaS products are technical products, they need dedicated documentation page.

I would be great to create something like that for this starter, I believe it could be useful, with the lack of similar starters for docs around for SvelteKit specifically.

In terms of visuals, as Saas Starter uses daisyUI, it would make sense to adjust to something like [their docs webpage](https://daisyui.com/docs/install/), for instance.

WDYT guys?

**Comment by scosman** [comment]
There are a ton of fantastic tools for making docs pages. Gitbook, [Material MKDocs](https://squidfunk.github.io/mkdocs-material/), [Docusaurus](https://github.com/facebook/docusaurus). Each is thousands of commits, hundreds of contributors, and tens of thousands of stars. You should use one of those 😀,

I just host one on a "docs" subdomain next to CMSaasStarter. They can also be compiled into static assets and served through svelte on the same domain.

I don't think it makes sense for this project to try to incorporate docs. Our version would just be a less featureful, and less well maintained version.
