### ISSUE TITLE
Add sitemap

### ISSUE THREAD

**Issue by jasongitmail** [CriticalMoments/CMSaasStarter#130]
This looks great. Hopefully templates like these will help the SvelteKit community to grow!

For SEO, it's missing a sitemap and robots.txt.

I might suggest Super Sitemap: https://github.com/jasongitmail/super-sitemap (I'm the author & searched deeply for a good one before building this.)

```ts
// /src/routes/sitemap.xml/+server.ts
import * as sitemap from 'super-sitemap';
import type { RequestHandler } from '@sveltejs/kit';

export const prerender = true;

export const GET: RequestHandler = async () => {
  return await sitemap.response({
    origin: 'https://example.com',
    excludeRoutePatterns: [
      '.*\\(admin\\).*', // i.e. exclude routes within admin group
    ],
  });
};
```
If you decide to add it, remember to include the `(admin)` group within the `excludeRoutePatterns` to omit those from your sitemap, and any others you might want to exclude.

Since your blog consists of svelte files, all those routes will be included automatically.

**Comment by scosman** [comment]
Thanks! I'll take a look soon!
