### ISSUE TITLE
Resend emails work locally but not on Cloudflare

### ISSUE THREAD

**Issue by otioss** [CriticalMoments/CMSaasStarter#131]
I followed the guide to set up email with Resend, added the API key to the .env file, and configured the DNS records in Cloudflare. Everything works fine locally, and emails are sent successfully when I test them. However, it doesn't work on Cloudflare.

I've checked the dev console, and there are no errors, and the DNS records in Cloudflare aren't proxied, as far as I know. Any ideas on what might be causing this issue?

**Comment by scosman** [comment]
99% of the time this is because you don't `await` the call to an async API like the mailer APIs. Cloudflare shuts down as soon as main thread exits, so you need to wait for it to complete. 

Can you check that and confirm/close if that's the case.

**Comment by otioss** [comment]
@scosman Thanks for the answer. The function is almost identical to sendAdminEmail() and it uses `await `

**Comment by scosman** [comment]
Are you calling it with await wherever you call it? What you are describing is almost definitely a missing await somewhere. Classic issue with serverless hosting like pages.

The stock version works; I can see it's sending welcome emails from cloud flare. 

I'm going to close since it looks like I think this issue lives in your adaption, not the template. But let us know if you find any details/issues.

**Comment by otioss** [comment]
Yes, I did use await when calling the function. I even tested it with your sendAdminEmail() function, but got the same result. The email sends successfully locally, but not when running on Cloudflare.

I'd appreciate any further assistance you could provide.

**Comment by scosman** [comment]
Can't help much from here. 

See the examples in code which do work:

// Send welcome email
      await sendUserEmail({

If you are sure you are awaiting properly, check your environment var setup matches in both envs.

**Comment by otioss** [comment]
@scosman Does the primary CNAME in Cloudflare need to be unproxied for sending emails? If so, this would disable many security features. I know that MX records shouldn't be proxied, but I'd like to understand if the CNAME proxy setting impacts email functionality.
