### ISSUE TITLE
SvelteKit 2 Upgrade

### ISSUE THREAD

**Issue by scosman** [CriticalMoments/CMSaasStarter#22]
We should probably do these at the same time. We can keep in a branch until Svelte 5 is released, but some folks will want to start on that branch.

Open to help from any Svelte enthusiasts who want to tackle this.

**Comment by scosman** [comment]
Someone took a start at this, but no PR so far: https://github.com/bbr27/nhancer-cmsass/commit/9baa9838816ad639103801351931f03cd5d6dbeb

**Comment by kryanbeane** [comment]
Hello, outside contributor here but user of this template — I would hold off on upgrading to Svelte 5. Literally every new feature is subject to change. Possibly going to be breaking lots of stuff in the template unless you wait until GA. Just my 2c

**Comment by scosman** [comment]
@kryanbeane oh yeah, no rush here. Even if someone starts, we'll keep it in a branch until GA.

**Comment by scosman** [comment]
General availability 😀. Aka Svelte 5 release (not beta).

**Comment by kryanbeane** [comment]
@scosman Cool sounds good. I've actually ported most of this template over to shadcn-svelte for a project I'm working on. Maybe a cool alternative for this daisy ui version. I might clean it up and make it a standalone repo if that's something others would be interested in using

**Comment by NDruce** [comment]
@kryanbeane Wow, it's actually what I'm going to start right now 😅

(recoding with shadcn)

Can you share your current progress on GitHub?

**Comment by scosman** [comment]
@kryanbeane cool! You can fork and we could link to it, or we could add it as a community extension branch: https://github.com/CriticalMoments/CMSaasStarter?tab=readme-ov-file#extensions

**Comment by bhupeshpr25** [comment]
@kryanbeane I would love to have a shadcn-svelte version 😀

**Comment by NDruce** [comment]
I found strong competitor of shadcn: preline.co
It has a lot of detailed designed components and it is insane

**Comment by NDruce** [comment]
I looking on DaisyUI examples and they're seems semi crooked :(

![image](https://github.com/CriticalMoments/CMSaasStarter/assets/33526036/4dfea4ae-907a-4ca6-92ba-8ab5dc650859)

![image](https://github.com/CriticalMoments/CMSaasStarter/assets/33526036/110b63c2-38ee-40e8-8a73-e50521cf2572)

![image](https://github.com/CriticalMoments/CMSaasStarter/assets/33526036/e081ae8b-4c89-43db-9dc5-9027ba0515f3)

![image](https://github.com/CriticalMoments/CMSaasStarter/assets/33526036/2db410e2-402a-4acb-b47d-c6f5f3bb81ab)

![image](https://github.com/CriticalMoments/CMSaasStarter/assets/33526036/1c73a958-fa0e-49b0-acab-915f8cf144d8)

shadcn & preline are the best for me (imho)

**Comment by scosman** [comment]
@NDruce sounds cool, but let's keep this thread for this issue topic (svelte 5 upgrade). Feel free to start a discussion on this if desired.

**Comment by scosman** [comment]
Splitting SvelteKit 2 from Svelte 5!
