### ISSUE TITLE
Upgrade to daisyUI 4

### ISSUE THREAD

**Issue by keybits** [CriticalMoments/CMSaasStarter#36]
daisyUI is currently at version 4.7.3.

They have an [upgrade guide for 3 to 4](https://github.com/saadeghi/daisyui/discussions/2507).

Would you accept a PR to upgrade to daisyUI v4.x?

**Comment by scosman** [comment]
Sounds like a great PR. Nothing in the migration doc is too concerning. 

Hardest part will likely be the sanity check each page works on desktop and mobile still.
