### ISSUE TITLE
Problem with Stripe integrations for one-off payments

### ISSUE THREAD

**Issue by Lucho-git** [CriticalMoments/CMSaasStarter#52]
![image](https://github.com/CriticalMoments/CMSaasStarter/assets/21086472/ec695164-f2e9-48a0-851c-8f5dd576ff22)

Using a stripe_price_id set to a one-off payment will return unknown SSE error.

"Unknown Error (SSE): If issue persists please contact us.",

![image](https://github.com/CriticalMoments/CMSaasStarter/assets/21086472/3f4b5770-8c4f-43c5-ae2f-bc2294f3b8b6)

**Comment by scosman** [comment]
The template is designed for subscriptions. Adapting to one time purchase should be fairly easy, but won't work without some tweaks. Even if we made this part work, the pricing page and admin console would also need changes.
