### ISSUE TITLE
Managing Subscription Throws a PSE Error

### ISSUE THREAD

**Issue by MaxBroome** [CriticalMoments/CMSaasStarter#55]
When logged in and clicking on "Manage Subscription" the user gets thrown an error page instead of going to the Stripe page.

Console log shows:

`Preloading data for /account/billing/manage failed with the following error: Unknown error (PSE). If issue persists, please contact us.
If this error is transient, you can ignore it. Otherwise, consider disabling preloading for this route. This route was preloaded due to a data-sveltekit-preload-data attribute. See https://kit.svelte.dev/docs/link-options for more info`

and

`GET http://localhost:5173/account/billing/manage 500 (Internal Server Error)`

**Screenshot:**

![image](https://github.com/CriticalMoments/CMSaasStarter/assets/56701581/fd367d7d-4259-44e5-b679-8b9e515df4e7)

**Comment by scosman** [comment]
Can you share config?

saasstarter.work runs on main and this issue doesn’t repo, so likely a config issue.

**Comment by MaxBroome** [comment]
Fixed! There was just an error in Stripe after I deleted all of my test data, I didn't re-setup the Customer Portal page.

Logs
`Customer ID obtained, creating billing portal session
Error creating billing portal session: StripeInvalidRequestError: You can’t create a portal session in test mode until you save your customer portal settings in test mode at https://dashboard.stripe.com/test/settings/billing/portal.
    at StripeError.generate (file:///C:/Users/broom/Documents/VSCode/ScoreScrape.io/Testing/Website/node_modules/stripe/esm/Error.js:7:20)
    at res.toJSON.then.StripeAPIError.message (file:///C:/Users/broom/Documents/VSCode/ScoreScrape.io/Testing/Website/node_modules/stripe/esm/RequestSender.js:102:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'StripeInvalidRequestError',
  raw: {
    message: 'You can’t create a portal session in test mode until you save your customer portal settings in test mode at https://dashboard.stripe.com/test/settings/billing/portal.',
    request_log_url: 'https://dashboard.stripe.com/test/logs/req_qZCTIr5ArM73Bp?t=1712812495',
    type: 'invalid_request_error',`

**Comment by zamakowany** [comment]
I have the same problem, if you still remember where you got the logs from I would be very grateful for the answer.

**Comment by scosman** [comment]
@zamakowany Search "PSE" in the code, and add a `console.log(e)` there to see the stripe error in more detail. Prob a setup issue.

**Comment by zamakowany** [comment]
Thanks, I'll give it a try

**Comment by zamakowany** [comment]
Which file to look in?

**Comment by evlim** [comment]
> Which file to look in?

\src\routes\(admin)\account\(menu)\billing\manage\+page.server.ts
