### ISSUE TITLE
Idea: Add CMSaasStarter to Vercel templates

### ISSUE THREAD

**Issue by carlosplanchon** [CriticalMoments/CMSaasStarter#56]
In order to facilitate the installation & deployment process, adding this project as a template on Vercel would be great.
https://vercel.com/templates

You can take ideas from this video.
https://www.youtube.com/watch?v=I7CFD99sp1g

**Comment by scosman** [comment]
Agree it would be cool! Unfortunately they don't seem to take submissions: https://github.com/orgs/vercel/discussions/4554

**Comment by carlosplanchon** [comment]
A way I saw is that you can generate your own deploy button

https://vercel.com/blog/deploy-button

https://vercel.com/docs/deployments/deploy-button#generate-your-own

**Comment by scosman** [comment]
Ah. Deploy button is an option, but they aren't adding any more to the template library as far as I've read (even if you add the button). 

It's also not quite ideal since supabase auth is needed. 

I'd take a PR for alternate deployment options like vercel. Shouldn't be too hard.

**Comment by scosman** [comment]
Okay, reopening! Vercel opened submissions back up.

We'd want a deploy button, and good env descriptions. Shouldn't be too hard. 

https://docs.google.com/forms/d/e/1FAIpQLSfU4EP7LkkUb2RX7vxxRJgq1iCiqYS6JW6CaZxMExR_hQR_hQ/viewform

**Comment by scosman** [comment]
Okay, added deploy button and submitted it to Vercel. It's up to Vercel to accept or reject now. But my work here is done!

**Comment by scosman** [comment]
They took a while, but they accepted it: https://vercel.com/templates/svelte/sveltekit-saas-starter
