### ISSUE TITLE
Svelte 5 Upgrade

### ISSUE THREAD

**Issue by scosman** [CriticalMoments/CMSaasStarter#77]
We should upgrade to Svelte 5 when it's released and stable.

https://svelte-5-preview.vercel.app/status

**Comment by scosman** [comment]
Svelte 5 is live!

Upgrade shouldn’t be too bad. If anyone wants to take a run at it, go for it. Otherwise I’ll get to it when I get to it 😀

**Comment by evlim** [comment]
#160

**Comment by scosman** [comment]
Preview: https://github.com/CriticalMoments/CMSaasStarter/pull/163

**Comment by scosman** [comment]
Done! 

Big thanks to @evlim for driving it.
