### ISSUE TITLE
Consider addding basic CRUD functionality

### ISSUE THREAD

**Issue by ndamofli** [CriticalMoments/CMSaasStarter#8]
First off congrats for this amazing starter kit. ! Basic CRUD funcionality (maybe a simple todo / notes list), would help less experienced devs and would demostrate the right practices for db operations, loading states and even validation. File uploads would also be a great addition.
Again, I for one am grateful for your contribution to the wonderful sveltekit community.

**Comment by scosman** [comment]
glad you like it!

The user profile is a good example of basic CRUD. It has loading states, server validation, client error UI, and server APIs. I think I’ll leave it at that, as adding non-core features would mean there's more manual work to tear out those when you start. Mostly a problem for the database tables, but would prob cause more headaches than it fixes (and the user profile is a pretty good CRUD sample).
