### ISSUE TITLE
New Feature: Admin Emailer

### ISSUE THREAD

**Issue by scosman** [CriticalMoments/CMSaasStarter#83]
Adding this as a new feature I think we need if anyone wants to take a run at a PR.

Basically: a way for a site owner to get an email when important things happen (contact us form, sign up, purchase). I added this in my private fork and it's super helpful. However, not happy with my library choice, so I'd want a cleaner version here.

## Part 1: Mailer

A typescript file that can send emails to the website owner. Basically expose `sendAdminsEmail(subject, html_body)`. No opt if the user hasn't set up correct env configs.

 - Env config with SMTP creds
 - Env config with "from/to" email addresses
 - Probably should use: https://nodemailer.com

I built this into my own fork, but made the mistake of using AWS SES APIs which are overly complex and host specific. SMTP crews and node mailer are way more flexible.

## Part 2: Integrate into key places in the app

Add integrations into places where the site admin might want to be notified:

 - Contact us
 - Sign up
 - Create profile
 - Purchases
 - Delete account

Also add env var for `admin_emails`. Defaults to  all, but you can override it in env to only get a subset of these.

## Part 3: Docs

Document the env vars and integration above in the README

**Comment by MaxBroome** [comment]
I already have some of this functionality with Supabase and webbooks. Whenever a new row is inserted into the contact_request table, it makes a webhook to a Python API I made that sends an email to me via SMTP that includes the form data with some formatting to make it look pretty.

I think including that feature in this repo would be sick. I'll take a look at it and maybe give it a shot!

**Comment by scosman** [comment]
Very cool!

Would love to just include it in the actual codebase (aka, the POST call for contract form), over a DB hook. Some folks are working on this with a non-Supabase Postgres. Would like to try to keep new features more pure Node/SMTP/Svelte, and less host specific code.

**Comment by internalG** [comment]
If not supabase how about OAuth?

**Comment by scosman** [comment]
OAuth for emails? Not sure I follow.

I'd prefer SMTP as it's a standard email API. That way you can use it on any email provider, including hosted (AWS SES, Resend, Sendgrid, etc), self hosted, or hosted personal (gmail, etc).

**Comment by internalG** [comment]
I mean the OAuth for google etc. This still uses auth js of supabase. Do we have other option to decouple it from supabase?

**Comment by scosman** [comment]
This thread is on a totally different topic (not auth related). Feel free to start a discussion on this topic to see if others are interested, but let’s keep this thread focused on this issue.
